# Generated by Django 5.0.3 on 2024-04-11 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0004_delete_comment"),
        ("comments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="blog",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="base.blog"
            ),
        ),
    ]
