# Generated by Django 5.0.3 on 2024-04-11 11:26

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0002_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="text",
            field=ckeditor.fields.RichTextField(max_length=2000),
        ),
    ]
