# Generated by Django 5.0.3 on 2024-03-28 18:16

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_blog_body_alter_blog_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='body',
            field=ckeditor.fields.RichTextField(default='...', max_length=6000),
        ),
    ]
