# Generated by Django 5.0.3 on 2024-04-11 11:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0003_alter_comment_text"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Comment",
        ),
    ]
