# Generated by Django 5.0.3 on 2024-04-02 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_blog_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='like_count',
            field=models.BigIntegerField(default=0),
        ),
    ]
