# Generated by Django 5.0.3 on 2024-04-02 19:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_blog_like_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='increment_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 3, 0, 36, 2, 691619)),
        ),
    ]
