# Generated by Django 5.0.3 on 2024-04-02 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_blog_increment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='increment_date',
            field=models.BigIntegerField(default=1),
        ),
    ]
